(function() {var implementors = {};
implementors['mpi'] = ["impl&lt;Req&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;Req&gt; for <a class='struct' href='mpi/request/struct.WaitGuard.html' title='mpi::request::WaitGuard'>WaitGuard</a>&lt;Req&gt; <span class='where'>where Req: <a class='trait' href='mpi/request/trait.Request.html' title='mpi::request::Request'>Request</a></span>","impl&lt;Req&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;Req&gt; for <a class='struct' href='mpi/request/struct.CancelGuard.html' title='mpi::request::CancelGuard'>CancelGuard</a>&lt;Req&gt; <span class='where'>where Req: <a class='trait' href='mpi/request/trait.Request.html' title='mpi::request::Request'>Request</a></span>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='type' href='https://doc.rust-lang.org/nightly/std/os/raw/type.c_int.html' title='std::os::raw::c_int'>c_int</a>&gt; for <a class='enum' href='mpi/topology/enum.Threading.html' title='mpi::topology::Threading'>Threading</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='type' href='https://doc.rust-lang.org/nightly/std/os/raw/type.c_int.html' title='std::os::raw::c_int'>c_int</a>&gt; for <a class='enum' href='mpi/topology/enum.CommunicatorRelation.html' title='mpi::topology::CommunicatorRelation'>CommunicatorRelation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='type' href='https://doc.rust-lang.org/nightly/std/os/raw/type.c_int.html' title='std::os::raw::c_int'>c_int</a>&gt; for <a class='enum' href='mpi/topology/enum.GroupRelation.html' title='mpi::topology::GroupRelation'>GroupRelation</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
